name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libfmt-dev libgtest-dev cmake
          sudo cmake -S /usr/src/googletest -B /usr/src/googletest/build
          sudo cmake --build /usr/src/googletest/build --target install
      - name: Run tests
        run: ./test.sh
